config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'questions#index'

  devise_for :users

  resources :questions do
    resources :answers, only: %i[create destroy update]
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  validates :body, presence: true
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :title, :body, presence: true
  has_many :answers, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[create]
  before_action :set_question, only: %i[create destroy update]
  before_action :set_answer, only: %i[destroy update]

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user

    if @answer.save
      flash[:notice] = 'Your answer successfully created.'
    else
      flash[:alert] = 'Cannot create an answer'
    end
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    redirect_to question_url(@question) unless current_user
    if @answer.destroy
      redirect_to question_url(@question), notice: 'Your answer successfully deleted'
    else
      render 'questions/show', status: :unprocessable_entity
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_question, only: %i[show edit update destroy]
  def index
    @questions = Question.all
  end

  def show
    @answers = @question.answers
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    redirect_to questions_path unless current_user
    if @question.destroy
      redirect_to questions_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'questions/answers' %>');
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |msg| %>
    $('.answer-errors').html('<%= j msg %>')
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'questions/answers' %>');
  $('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
  });
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : 'QnA'
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    p = answer.body
    - if user_signed_in?
      p = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      p
        = form_with(model: [@question, @answer], local: false, html: { id: "edit-answer-#{answer.id}" }) do |f|
          = f.label :body, 'Answer'
          = f.text_area :body
          = f.submit 'Save'

app/views/questions/index.html.slim
- @questions.each do |question|
  = link_to question.title, question_path(question)
  = question.body

p
  = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_with(model: @question) do |f|
  - if @question.errors.any?
    - @question.errors.full_messages.each do |msg|
      = msg

  = f.label :title
  = f.text_field :title

  = f.label :body
  = f.text_area :body

  = f.submit 'Create'

app/views/questions/show.html.slim
h1 = @question.title
p = @question.body

.answers
  = render 'answers'

= form_with(model: [@question, @answer], local: false) do |f|
  p
    = f.label :body, 'Your answer'
    .answer-errors
    = f.text_area :body

  = f.submit 'Create'